export default {
    dark_purple: '#474677',
    medium_purple: '#556289',
    light_purple: '#8892AD',
    white: '#FFFFFF',
    dark_gray: '#3B4469',
    gray: '#CCCCCC',
    light_gray : '#DDDDDD',
    ultralight_gray: '#EEEEEE',
    black: '#171919',
    urgent_red: '#FF7081',
    red: '#FF0000',
    urgent_orange: '#FBC580',
    orange: 'FF8000',
    urgent_blue: '#7CABFF',
    blue: '#7CA000',
    green: 'green',
    blue: 'blue',
    orange: 'orange',
    steel: 'gray',
    dark:'#333333',
    light:'#EEEEEE',
    purple: 'purple',
}